language: ruby
rvm:
- 2.3.3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build

script: bundle exec jekyll build && bundle exect rake test
