# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            János Rusiczki
tagline:          Your average weblog
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://jekyll.rusiczki.net
baseurl:          /
permalink:        /:year/:month/:day/:title/

author:
  name:           'János Rusiczki'
  url:            https://twitter.com/janosrusiczki

paginate:         5

# Custom vars
version:          2.1.0
plugins:
  - jekyll-paginate
  - jekyll_asset_pipeline
  - jekyll-tidy

github:
  repo:           https://github.com/poole/hyde

disqus:
  username: kitsched

algolia:
  application_id: 'WMKRED0LJU'
  index_name:     'janosrusiczki'

exclude:
  - README.md
