# Dependencies
markdown: kramdown
highlighter: rouge

# Setup
title: János Rusiczki
tagline: Your average weblog
description: Ruby & Web Developer. Photographer. Drone Pilot. Snowboarder. Etc.
url: https://www.rusiczki.net
baseurl: /
permalink: /:year/:month/:day/:title/

author:
  name: János Rusiczki
  url: https://twitter.com/janosrusiczki

paginate: 5
paginate_path: '/page/:num'

# Custom vars
plugins:
  - jekyll-paginate
  - jekyll_asset_pipeline
  - jekyll-tidy
  - jekyll-feed
  - jekyll-sitemap

disqus:
  username: kitsched

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

algolia:
   application_id: WMKRED0LJU
   index_name: janosrusiczki
   search_only_api_key: 925c854d627ec98d0ca55addbecd6b82

github:
  repository_url: https://github.com/janosrusiczki/janosrusiczki
  branch: master

defaults:
  -
    scope:
      path: 'page'
    values:
      sitemap: false
